
name: 'billong'
version: '2.0'
config-version: 2

profile: 'billong'

model-paths: ['models']
seed-paths: [data']
test-paths: ['tests']
analysis-paths: ['analysis']
macro-paths: ['macros']

#snapshot-paths: [directorypath]
#docs-paths: [directorypath]
#asset-paths: [directorypath]

#log-path: directorypath
#packages-install-path: directorypath
target-path: 'target'
clean-targets:
    - "target"
    - "dbt_modules"


models:
  billong: # MUST BE SOME NAME AS PROJECT
      pre-hook: "{{ logging.log_model_start_event() }}"
      post-hook: "{{ logging.log_model_end_event() }}"
      
      1-marts:
        materialized: table
        schema: marts
        tags: marts
      
      2-staging:
        materialized: table
        schema: staging
        tags: staging
        post-hook:
          - "IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = '{{this.table}}')  BEGIN CREATE CLUSTERED COLUMNSTORE INDEX {{this.table}} ON {{this}} END "   ## ONLY WHEN OLD SQL SERVER
      
      3-land:
        materialized: view
        schema: land
        tags: land

seeds:
  billong:
    enabled: true
    schema: seeds

# semantic-models:
#  <semantic-model-configs>

#snapshots:
#  <snapshot-configs>

#sources:
#  <source-configs>
  
#tests:
#  <test-configs>

#vars:
#  <variables>

#on-run-start: sql-statement | [sql-statement]
#on-run-end: sql-statement | [sql-statement]


#dispatch:
#  - macro_namespace: packagename
#    search_order: [packagename]