version: 2

models:

  - name: england_0019
    description: Game result from england Season 2000 - 2019
    columns:
      - name: match_key
        description: Primary key
        tests:
          - not_null
          - unique
