version: 2

models:

  - name: football_results
    description: All results
    columns:
      - name: match_key
        description: from_case_key
        tests:
          - not_null
          - unique
